### ISSUE TITLE
From feedback

### ISSUE THREAD

**Issue by kentaromiura** [kentaromiura/cristian.tokyo#1]
Link are not standing out, consider adding 
```css
:not(sup) > a[href]::before{content:"["}
:not(sup) > a[href]::after{content:"]"}
```
